### ISSUE TITLE
Signatures lost after merge

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.signatures#1]
The extension stores the signatures in _one_ setting entry, internally mapped by ``contact_id``. This, however, is not subject to civicrm's merge process, since the ``contact_id`` is not exposed.

It would be better to use the ``contact_id`` column in the settings, and thus store each signature in a different entry, because this would probably (please double check!) be treated correctly when contacts are merged.

**Comment by bjendres** [comment]
It's worth noting, that if both contacts to be merged have a signature record, only one of those records will prevail. This scenario would be a lot of work to implement, and should be the exception.

**Comment by jensschuppe** [comment]
... "one of those" meaning either the merged (then deleted) contact's signatures record (if it exists) or the remaining contact's signatures record (if the merged contact doesn't have a signatures record).
