### ISSUE TITLE
Incompatible with PHP 8.1

### ISSUE THREAD

**Issue by ghost** [systopia/de.systopia.signatures#13]
It seems that this lovely extension is not compatible with PHP 8.1. 

Tried on WordPress 6.1.1 with CiviCRM 5.55.2 on PHP 8.1.13.

**Comment by bjendres** [comment]
> It seems that this lovely extension is not compatible with PHP 8.1.

Yes, that's very likely :) Thanks for reporting.

Would you be able to provide a PR? It would still have to be PHP 7.4 compatible, though.

**Comment by ghost** [comment]
PHP 7.4 support is fine. 
I'll try to update it. Never made this before...

**Comment by ghost** [comment]
Array and string offset access syntax with curly braces is deprecated: signatures.civix.php, 246

**Comment by bjendres** [comment]
@eptbertram can you confirm, that the extension is fully compatible with PHP8.0 and 8.1?

**Comment by ghost** [comment]
@bjendres it's working fine with PHP8.1. I didn't checked 8.0.
